# coding: utf-8

"""
    Plaid Institutions API

    API for searching Plaid institutions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.institutions_search_post_request import InstitutionsSearchPostRequest

class TestInstitutionsSearchPostRequest(unittest.TestCase):
    """InstitutionsSearchPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstitutionsSearchPostRequest:
        """Test InstitutionsSearchPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstitutionsSearchPostRequest`
        """
        model = InstitutionsSearchPostRequest()
        if include_optional:
            return InstitutionsSearchPostRequest(
                client_id = '',
                secret = '',
                query = '',
                products = [
                    ''
                    ],
                country_codes = [
                    ''
                    ]
            )
        else:
            return InstitutionsSearchPostRequest(
                client_id = '',
                secret = '',
                query = '',
                country_codes = [
                    ''
                    ],
        )
        """

    def testInstitutionsSearchPostRequest(self):
        """Test InstitutionsSearchPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
