# coding: utf-8

"""
    Plaid Institutions API

    API for searching Plaid institutions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.institution import Institution

class TestInstitution(unittest.TestCase):
    """Institution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Institution:
        """Test Institution
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Institution`
        """
        model = Institution()
        if include_optional:
            return Institution(
                institution_id = '',
                name = '',
                country_codes = [
                    ''
                    ],
                url = '',
                logo = '',
                primary_color = '',
                products = [
                    ''
                    ]
            )
        else:
            return Institution(
        )
        """

    def testInstitution(self):
        """Test Institution"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
