# coding: utf-8

# flake8: noqa
"""
    Plaid Institutions API

    API for searching Plaid institutions.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.institution import Institution
from openapi_client.models.institutions_search_post200_response import InstitutionsSearchPost200Response
from openapi_client.models.institutions_search_post_request import InstitutionsSearchPostRequest
